[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "fpdf2>=2.8.8",
    "langchain>=1.4.0",
    "langchain-openai>=1.6.2",
    "langfuse>=4.15.4",
    "langgraph>=1.2.11",
    "matplotlib>=3.11.2",
    "pandas>=3.0.5",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "tavily-python>=0.8.4",
    "uvicorn>=0.53.0",
]
